package com.example.medcare.utils

object Constants {
    private const val PROJECT_NAME = "com.example.medcare."
    const val SHARED_PREF_ROOT = PROJECT_NAME + "SHARED_PREF"
    const val SHARED_DEFAULT = ""
    const val SHARED_USER_ID = PROJECT_NAME + "USER_ID"
    const val SHARED_PASSWORD = PROJECT_NAME + "PASSWORD"
    const val SHARED_EMAIL = PROJECT_NAME + "EMAIL"
    const val SHARED_USER = PROJECT_NAME + "USER"
    const val SHARED_NOTIFICATION_REMINDER = PROJECT_NAME + "NOTIFICATION_REMINDER"
    const val SHARED_NOTIFICATION_FEED_BACK = PROJECT_NAME + "NOTIFICATION_FEED_BACK"
    const val SHARED_NOTIFICATION_MESSAGE = PROJECT_NAME + "NOTIFICATION_MESSAGE"
    const val SHARED_NOTIFICATION_DOSAGE = PROJECT_NAME + "NOTIFICATION_DOSAGE"
    const val SHARED_NOTIFICATION_MUSIC = PROJECT_NAME + "NOTIFICATION_MUSIC"
    const val SHARED_NOTIFICATION_SHAKE = PROJECT_NAME + "NOTIFICATION_SHAKE"
}